[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "6813ca4fcac083a88da1c6fedaf5b4090e10e677"
os = "macos"

    [[Cuba.download]]
    sha256 = "a2434b4f7f4b3d3f9af04aaaab01e0dae7d1bd23ec442b4d905ab1e152d0d303"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.aarch64-apple-darwin.tar.gz"
[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "5941a1364458dd2d5a736e605f5d4cef7bd8c3a9"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "44eac721bba7c0acf2d5e34327d38e2a1a85c8b52f251f787092e97e3a7cfe36"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.aarch64-linux-gnu.tar.gz"
[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "f9fa9441c5709032cffd180c2cb0c1e00c8abae8"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "4ffda9747c14f92a3f353722e3ef8d200a1c47530b555342f1376524464466af"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.aarch64-linux-musl.tar.gz"
[[Cuba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e9fe7bbd17d13a15039ca77eee1426dfb1225bc"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "6f0042236480277832fad6f3cbb831c14036f50d6c3dd36d9589336c43820c93"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Cuba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3bd8df653a0a5a3626fa817aad32423061447167"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "8aaadb211b0cc1a7ff7a2a9eec44d95cb02e1fd73d074b629ac34ffa06d69d6f"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.armv6l-linux-musleabihf.tar.gz"
[[Cuba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be26755a9f2681ed56b233ce08726228af7146a8"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "6255a247ec329a3b6d56c2e266e85864f6df49cbc5acbc83321ffb348198d0bb"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Cuba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a095cdfd741b91def38a1195d18c25d46e2b18af"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "94db4c99874ee8306ad8e9d26d5384218722d6a878e3f3579e30e6654e19a8ad"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.armv7l-linux-musleabihf.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "21eb7e3bc5cc7525120c709fb28f5d42b09f4761"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "046420cd01b161474e220a9037c987eba01b747a68fb81f0d561b5e45ace0d7a"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.i686-linux-gnu.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "00de36af257e8c5c482297b6fe22a13bce9462cc"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "eda84ac4846a2e299b1c42da22af6ec735961c4f5872120b9d89a13525f77012"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.i686-linux-musl.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "2dca541a3a383cc98d3879f83ba8ad79c5924bed"
os = "windows"

    [[Cuba.download]]
    sha256 = "cface4036996d78fde4990031a629ff85b0d2e5753a91fdccc8d7c2e290b28e5"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.i686-w64-mingw32.tar.gz"
[[Cuba]]
arch = "powerpc64le"
git-tree-sha1 = "e208c14a94997e9196e0854abe002f8778000dc8"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "9106b8d15078c4ce5235dbede3871f13911530a4e51b120e09bd183155f11b96"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.powerpc64le-linux-gnu.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "e9c9d8e7cc85f83db3e115731cf1fec7dad98f32"
os = "macos"

    [[Cuba.download]]
    sha256 = "b767719aea99b4cb83e4091dcfea90f2dfa9a532ce96c05bb12eb6d0f77d85f2"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.x86_64-apple-darwin.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "f8d9dba7cbae70f6d961447bd8d96ee5f6045440"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "0c3aaf6e953b9e57e24a7f70cd8ca63623a72ef1880b67d9af4f78c9c7f481ef"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.x86_64-linux-gnu.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "50ba4af17ac22e087551d359cb3eed212e9bf24f"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "b33b56c5a9ee2835ef6be461e796e7a81060a5e7622e3ca09dfefdfa4d070505"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.x86_64-linux-musl.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "51e51600ec01a5dc3563ade4733a5e186f50cd0c"
os = "freebsd"

    [[Cuba.download]]
    sha256 = "39979d77c79ae542a303c8cca1e180d10ff252b1ed37504137b0c4f575cc3fa8"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.x86_64-unknown-freebsd.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "db988ae0ca9539daba60e7810e78cdd8135bbe7a"
os = "windows"

    [[Cuba.download]]
    sha256 = "3e0f09158c75a4b5fe5736ecd0de41c8d23334d459c221c4c173f0a99a969d47"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+0/Cuba.v4.2.2.x86_64-w64-mingw32.tar.gz"
