[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "d3bc90ef90c2904c9b885b31570ecf889fbabd1f"
os = "macos"

    [[Cuba.download]]
    sha256 = "c4c1606f112a43fa10ef03dfea03ee8cfec734b2446321b6482958a15ea0a703"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.aarch64-apple-darwin.tar.gz"
[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "a596510faa7bd84d6f928742893baa4feb0732fd"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "0864025348e19018f078d5717ed07b05b58d7da87a9c13a67ed7d389e0daca6d"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.aarch64-linux-gnu.tar.gz"
[[Cuba]]
arch = "aarch64"
git-tree-sha1 = "9c338ad400e5d7afcddd52db459e8a3c251ca1a1"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "b7be8146b2d75184f8ea381b1249bfeebcf655991cfab440094f939696f7bf30"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.aarch64-linux-musl.tar.gz"
[[Cuba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39ff6a96bde64cf0010ae1d629945bb453dff39f"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "3e1be0032abe6a650a8e28e92b631b0fcc5139eb029b53d59ac7fb9b3d6b3881"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Cuba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05cd2699cca43caa0dbab461ea63a755309c3218"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "2aae3236a5ca5608300249cbe2a3f701f7caec60289119bbd5ab6514953e14d8"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.armv6l-linux-musleabihf.tar.gz"
[[Cuba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a45bc91a2c0d69da2842497837bb0778c282eb1b"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "b59e9ebb83d64ef42b724d1d28b5e5d8a17658916d4fcb6b285fd744f38679c6"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Cuba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c094f0f36dc02b17b5cb2071172acd4b6d30b96f"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "3026074fa4e8d2096b811eb14b6da427bf8d9e42ab3ddce704316444309b7aa7"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.armv7l-linux-musleabihf.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "ba9110f0887796bca3b3ab6440f2979683f03d5f"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "3c3db072ea6b56a4618a77a660776124d95e7d172189a746f83a182912c54bc4"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.i686-linux-gnu.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "8b9d420cfb98bf5b4fb7b05724b1fb3247c8c250"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "d5426ad8ebb0ff60859c5a084fb80676998c666dcc0d30695d1b87b4aad953b2"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.i686-linux-musl.tar.gz"
[[Cuba]]
arch = "i686"
git-tree-sha1 = "485fb6a1dd84d5c4bbd5add20c4cd414dcbd3f4b"
os = "windows"

    [[Cuba.download]]
    sha256 = "ae1d4aa9be94b48502f55874202ed531f5072eb0d585d090d0a3249cd78771c6"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.i686-w64-mingw32.tar.gz"
[[Cuba]]
arch = "powerpc64le"
git-tree-sha1 = "f270610f2d78c301a9c5b0010216809af8ef0a67"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "7e9a6460f4c38001f34cf708b816ba9f3a4f8591eccba2b1203f6c42cb5c189f"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.powerpc64le-linux-gnu.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "f8166b945cf2f4a8c3f2f8d201dbcba524f95190"
os = "macos"

    [[Cuba.download]]
    sha256 = "12e7f7eacd8a779bf98aabf1c06dbbf0c8d42149bfa5e14c6f6ba52e2751c28f"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.x86_64-apple-darwin.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "98f4aefddb92eaf8827431e50659e5206b9b0f0f"
libc = "glibc"
os = "linux"

    [[Cuba.download]]
    sha256 = "7a3af7f7efd5a9a040eacd25017e5295b83c99aa9eed832da7a56fa4b52c202e"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.x86_64-linux-gnu.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "c4ebe244280791ad3f9a48985d0d6a73f71631e4"
libc = "musl"
os = "linux"

    [[Cuba.download]]
    sha256 = "716e7f662163550a823d510ffe1fb0e37ffe88bfec3f377afb398b0103d64e16"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.x86_64-linux-musl.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "4ab6d6594c80fa0c7629ee732b465acafe8116ad"
os = "freebsd"

    [[Cuba.download]]
    sha256 = "49fbd6920d36669d6a1adc9b8830b1d914ddee12ba611f621c2cd95f6158cacc"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.x86_64-unknown-freebsd.tar.gz"
[[Cuba]]
arch = "x86_64"
git-tree-sha1 = "315f858f69d07e059d601f88b998495f20ae4c57"
os = "windows"

    [[Cuba.download]]
    sha256 = "54b9057685ab4ea671be328ec4da4f8486db6ece9bd6ba9627393ab05c059de0"
    url = "https://github.com/JuliaBinaryWrappers/Cuba_jll.jl/releases/download/Cuba-v4.2.2+1/Cuba.v4.2.2.x86_64-w64-mingw32.tar.gz"
