# Autogenerated wrapper script for Cuba_jll for x86_64-apple-darwin
export libcuba

JLLWrappers.@generate_wrapper_header("Cuba")
JLLWrappers.@declare_library_product(libcuba, "@rpath/libcuba.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcuba,
        "lib/libcuba.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
