# Autogenerated wrapper script for Cuba_jll for x86_64-w64-mingw32
export libcuba

JLLWrappers.@generate_wrapper_header("Cuba")
JLLWrappers.@declare_library_product(libcuba, "libcuba.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcuba,
        "bin\\libcuba.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
